# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.
#
name: 'Delivery'

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Integration" ]
    types: [ success ]
    branches: [ main ]

env:
  PROJECT_ID: 'goffeine-468309'
  REGION: 'europe-west3'
  SERVICE: 'goffeine'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/239871382403/locations/global/workloadIdentityPools/github/providers/goffeine'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Cloud Run
        run: gcloud run deploy goffeine --image europe-west3-docker.pkg.dev/goffeine-468309/goffeine-hub/goffeine:latest --region europe-west3 --allow-unauthenticated --project ${{ env.PROJECT_ID }} --max-instances=2 --service-account=github-actions@goffeine-468309.iam.gserviceaccount.com
