# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.
#

name: 'CD'

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]
    branches: [ main ]
  
env:
  PROJECT_ID: 'goffeine'
  REGION: 'europe-west3'
  SERVICE: 'goffeine'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/239871382403/locations/global/workloadIdentityPools/github/providers/goffeine'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: goffeine
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: push image
        run: gcloud builds submit --tag europe-west3-docker.pkg.dev/goffeine/goffeine/goffeine:latest

      - name: Deploy to Cloud Run
        run: gcloud run deploy goffeine --image europe-west3-docker.pkg.dev/goffeine/goffeine/goffeine:latest --region europe-west3 --allow-unauthenticated --project goffeine --max-instances=2
