# This workflow provides basic CI for Goffeine.
# The first build job should provide early feedback. The second job "quality_check" runs tests,
# validates the formatting and makes use of the tools staticcheck and gosec.


name: 'Integration'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build, test and check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.865

      - name: Build the application
        run: make build

      - name: Run tests
        run: go test -v ./... -cover

      - name: run go fmt
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...

  docker:
    name: Create container image
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: goffeine
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: push image
        run: gcloud builds submit --tag europe-west3-docker.pkg.dev/goffeine/goffeine/goffeine:latest

