# This workflow provides basic CI for Goffeine.
# The first build job should provide early feedback. The second job "quality_check" runs tests,
# validates the formatting and makes use of the tools staticcheck and gosec.


name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: Install Templ
      run: go install github.com/a-h/templ/cmd/templ@v0.3.819

    - name: Build
      run: make build

  quality_check:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.819

      - name: Build the application
        run: make build

      - name: Run tests
        run: go test -v ./... -cover

      - name: run go fmt
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...
